export default {
    GET_MATCHES: 'GET_MATCHES',
    GET_MATCHES_SUCCESS: 'GET_MATCHES_SUCCESS',
    GET_MATCHES_FAILURE: 'GET_MATCHES_FAILURE',

    GET_LIVESTREAM: 'GET_LIVESTREAM',
    GET_LIVESTREAM_SUCCESS: 'GET_LIVESTREAM_SUCCESS',
    GET_LIVESTREAM_FAILURE: 'GET_LIVESTREAM_FAILURE',

    SET_CHANNEL: 'SET_CHANNEL'
}