export default {
    GET_MATCHES: 'GET_MATCHES',
    GET_MATCHES_SUCCESS: 'GET_MATCHES_SUCCESS',
    GET_MATCHES_FAILURE: 'GET_MATCHES_FAILURE',

    GET_LIVESTREAM: 'GET_LIVESTREAM',
    GET_LIVESTREAM_SUCCESS: 'GET_LIVESTREAM_SUCCESS',
    GET_LIVESTREAM_FAILURE: 'GET_LIVESTREAM_FAILURE',

    SET_CHANNEL: 'SET_CHANNEL',

    GET_CHANNEL: 'GET_CHANNEL',
    GET_CHANNEL_SUCCESS: 'GET_CHANNEL_SUCCESS',
    GET_CHANNEL_FAILURE: 'GET_CHANNEL_FAILURE',

    POST_URL: 'POST_URL',
    POST_URL_SUCCESS: 'POST_URL_SUCCESS',
    POST_URL_FAILURE: 'POST_URL_FAILURE',

}