export default {
    AUTHENTICATED: 'AUTHENTICATED',
    UN_AUTHENTICATED: 'UN_AUTHENTICATED',

    POST_URL: 'POST_URL',
    POST_URL_SUCCESS: 'POST_URL_SUCCESS',
    POST_URL_FAILURE: 'POST_URL_FAILURE',

    SEARCH: 'SEARCH',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE'

}